Repository doctrine/collections, pull requests merged in 2019-11, with the labels that each got.

#213 Remove PHP 7.4 from `allow_failures` matrix
  .travis.yml
Labels: Enhancement

#215 Enhancement: improve test suite
  composer.json
  composer.lock
  tests/Doctrine/Tests/Common/Collections/AbstractLazyCollectionTest.php
  tests/Doctrine/Tests/Common/Collections/BaseArrayCollectionTest.php
Labels: Enhancement

#218 reflect that ExpressionBuilder#andX() and orX() params are variadic in PHPDoc
  lib/Doctrine/Common/Collections/ExpressionBuilder.php
Labels: Bug, Documentation

#222 Fix of branch name for doctrine website build
  .doctrine-project.json
Labels: Documentation
