Repository doctrine/collections, pull requests merged in 2019-03, with the labels that each got.

#131 ClosureExpressionVisitor > Don't duplicate the accessor when the field already starts with it
  lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php
  tests/Doctrine/Tests/Common/Collections/ClosureExpressionVisitorTest.php
Labels: Bug

#178 Updated doctrine/coding-standard to 6.0
  composer.json
  composer.lock
  lib/Doctrine/Common/Collections/AbstractLazyCollection.php
  lib/Doctrine/Common/Collections/ArrayCollection.php
  lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php
  lib/Doctrine/Common/Collections/Expr/ExpressionVisitor.php
Labels: Enhancement

#177 Generify collections using Psalm
  .scrutinizer.yml
  .travis.yml
  composer.json
  composer.lock
  lib/Doctrine/Common/Collections/AbstractLazyCollection.php
  lib/Doctrine/Common/Collections/ArrayCollection.php
  lib/Doctrine/Common/Collections/Collection.php
  lib/Doctrine/Common/Collections/Selectable.php
  psalm.xml.dist
Labels: Enhancement

#183 Add infection as testing tool
  .gitignore
  .travis.yml
  composer.json
  composer.lock
  infection.json.dist
Labels: Enhancement

#185 Update Collection::filter docblock to add key parameter to closure
  lib/Doctrine/Common/Collections/Collection.php
Labels: Enhancement

#186 Use @psalm-template annotation to avoid clashes
  lib/Doctrine/Common/Collections/AbstractLazyCollection.php
  lib/Doctrine/Common/Collections/ArrayCollection.php
  lib/Doctrine/Common/Collections/Collection.php
  lib/Doctrine/Common/Collections/Selectable.php
Labels: Bug

#187 Documentation for serialization of collections
  docs/en/serialization.rst
  docs/en/sidebar.rst
Labels: Documentation
