Repository doctrine/collections, pull requests merged in 2021-08, with the labels that each got.

#278 Bump doctrine/coding-standard
  composer.json
  lib/Doctrine/Common/Collections/AbstractLazyCollection.php
  lib/Doctrine/Common/Collections/ArrayCollection.php
  lib/Doctrine/Common/Collections/Collection.php
  lib/Doctrine/Common/Collections/Selectable.php
  phpcs.xml.dist
Labels: Improvement

#277 Add ReturnTypeWillChange where necessary
  .github/workflows/coding-standards.yml
  .github/workflows/static-analysis.yml
  lib/Doctrine/Common/Collections/AbstractLazyCollection.php
  lib/Doctrine/Common/Collections/ArrayCollection.php
  phpstan.neon.dist
  psalm.xml.dist
Labels: Improvement

#280 Add explicit `@return` type next to `#[ReturnTypeWillChange]`
  lib/Doctrine/Common/Collections/AbstractLazyCollection.php
  lib/Doctrine/Common/Collections/ArrayCollection.php
Labels: Documentation

#282 Revert "Update Psalm and fix a few issues"
  lib/Doctrine/Common/Collections/AbstractLazyCollection.php
  lib/Doctrine/Common/Collections/ArrayCollection.php
Labels: Bug
