Repository doctrine/collections, pull requests merged in 2022-09, with the labels that each got.

#327 Make signature compatible with parent signature
  lib/Doctrine/Common/Collections/ArrayCollection.php
Labels: Bug

#322 Extract read-only part of Collection
  docs/en/index.rst
  lib/Doctrine/Common/Collections/AbstractLazyCollection.php
  lib/Doctrine/Common/Collections/ArrayCollection.php
  lib/Doctrine/Common/Collections/Collection.php
  lib/Doctrine/Common/Collections/ReadableCollection.php
  psalm.xml.dist
Labels: Static Analysis

#330 Make Selectable template covariant
  lib/Doctrine/Common/Collections/Selectable.php
Labels: BC break, Static Analysis

#332 Add missing param type declarations
  UPGRADE.md
  lib/Doctrine/Common/Collections/AbstractLazyCollection.php
  lib/Doctrine/Common/Collections/ArrayCollection.php
Labels: BC break

#338 Fix markup
  UPGRADE.md
Labels: Documentation

#339 Use a shallower tree
  composer.json
  phpcs.xml.dist
  phpstan.neon.dist
  phpunit.xml.dist
  psalm.xml.dist
  src/AbstractLazyCollection.php
  src/ArrayCollection.php
  src/Collection.php
  src/Criteria.php
  src/Expr/ClosureExpressionVisitor.php
  src/Expr/Comparison.php
  src/Expr/CompositeExpression.php
  src/Expr/Expression.php
  src/Expr/ExpressionVisitor.php
  src/Expr/Value.php
  src/ExpressionBuilder.php
  src/ReadableCollection.php
  src/Selectable.php
  tests/Common/Collections/AbstractLazyArrayCollectionTest.php
  tests/Common/Collections/AbstractLazyCollectionTest.php
  tests/Common/Collections/ArrayCollectionTest.php
  tests/Common/Collections/BaseArrayCollectionTest.php
  tests/Common/Collections/BaseCollectionTest.php
  tests/Common/Collections/ClosureExpressionVisitorTest.php
  tests/Common/Collections/CollectionTest.php
  tests/Common/Collections/CriteriaTest.php
  tests/Common/Collections/DerivedCollectionTest.php
  tests/Common/Collections/Expr/ComparisonTest.php
  tests/Common/Collections/Expr/CompositeExpressionTest.php
  tests/Common/Collections/Expr/ValueTest.php
  tests/Common/Collections/ExpressionBuilderTest.php
  tests/DerivedArrayCollection.php
  tests/LazyArrayCollection.php
Labels: Improvement

#340 Mark closure arguments as always-provided
  src/ReadableCollection.php
Labels: Bug, Static Analysis

#343 Restore return types
  UPGRADE.md
  phpcs.xml.dist
  phpstan.neon.dist
  src/AbstractLazyCollection.php
  src/ArrayCollection.php
  src/Collection.php
  src/Criteria.php
  src/Expr/ClosureExpressionVisitor.php
  src/Expr/Comparison.php
  src/Expr/CompositeExpression.php
  src/Expr/Expression.php
  src/Expr/ExpressionVisitor.php
  src/Expr/Value.php
  src/ExpressionBuilder.php
  src/ReadableCollection.php
  src/Selectable.php
Labels: BC break
