Repository doctrine/collections, pull requests merged in 2022-08, with the labels that each got.

#312 Stop returning true from Collection::add()
  UPGRADE.md
  lib/Doctrine/Common/Collections/AbstractLazyCollection.php
  lib/Doctrine/Common/Collections/ArrayCollection.php
  lib/Doctrine/Common/Collections/Collection.php
  phpcs.xml.dist
Labels: BC break

#313 Update phpdoc of the AbstractLazyCollection
  lib/Doctrine/Common/Collections/AbstractLazyCollection.php
  phpstan.neon.dist
Labels: Static Analysis

#314 Make `Selectable#matching` return `Collection`
  lib/Doctrine/Common/Collections/Selectable.php
  tests/Doctrine/Tests/Common/Collections/BaseCollectionTest.php
Labels: Improvement

#325 Upgrade to doctrine/coding-standard 10
  composer.json
  lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php
  lib/Doctrine/Common/Collections/Expr/Comparison.php
  lib/Doctrine/Common/Collections/Expr/CompositeExpression.php
  lib/Doctrine/Common/Collections/Expr/Expression.php
  lib/Doctrine/Common/Collections/Expr/Value.php
  tests/Doctrine/Tests/Common/Collections/BaseArrayCollectionTest.php
  tests/Doctrine/Tests/Common/Collections/ClosureExpressionVisitorTest.php
  tests/Doctrine/Tests/Common/Collections/CollectionTest.php
  tests/Doctrine/Tests/Common/Collections/Expr/ComparisonTest.php
  tests/Doctrine/Tests/Common/Collections/Expr/CompositeExpressionTest.php
  tests/Doctrine/Tests/Common/Collections/Expr/ValueTest.php
  tests/Doctrine/Tests/Common/Collections/ExpressionBuilderTest.php
  tests/Doctrine/Tests/DerivedArrayCollection.php
  tests/Doctrine/Tests/LazyArrayCollection.php
Labels: Improvement
