Repository doctrine/collections, pull requests merged in 2024-02, with the labels that each got.

#390 Use a stable version of the guides-cli
  .github/workflows/documentation.yml
  docs/en/sidebar.rst
Labels: CI

#393 Upgrade to PHPUnit 10
  composer.json
  phpunit.xml.dist
  tests/AbstractLazyArrayCollectionTest.php
  tests/AbstractLazyCollectionTest.php
  tests/ArrayCollectionTest.php
  tests/ArrayCollectionTestCase.php
  tests/CollectionTest.php
  tests/CollectionTestCase.php
  tests/Expr/CompositeExpressionTest.php
Labels: Test Suite

#394 reduce method: more accurate types
  src/ReadableCollection.php
Labels: Static Analysis

#389 Introduce Order enum
  UPGRADE.md
  docs/en/expressions.rst
  src/ArrayCollection.php
  src/Criteria.php
  src/Order.php
  tests/BaseArrayCollectionTest.php
  tests/CollectionTest.php
  tests/CriteriaTest.php
Labels: Deprecation

#395 Update expressions.rst: Adding `use Doctrine\Common\Collections\Order;`
  docs/en/expressions.rst
Labels: Documentation

#398 Add missing upgrade note
  UPGRADE.md
Labels: Documentation

#401 Cleanup deprecations
  UPGRADE.md
  src/Criteria.php
  tests/ArrayCollectionTestCase.php
  tests/CriteriaTest.php
Labels: BC break

#402 Update branch metadata
  .doctrine-project.json
Labels: Documentation
